language: ruby
rvm:
  - 2.2
env:
  - MYSQL_ALLOW_EMPTY_PASSWORD="1"
  - RSPEC_RETRY_RETRY_COUNT="3"
  - RAILS_ENV="test"
  - SIMPLECOV="true"
  - USE_DB="true"
  - USE_BUNDLE_INSTALL="true"
  - GIT_DEPTH="20"
  - PHANTOMJS_VERSION="2.1.1"
services:
  - mysql
before_script:
  - mysql -e 'create database gitlabhq_test;' -uroot
  - source ./scripts/prepare_build.sh
  - cp config/gitlab.yml.example config/gitlab.yml
  - bundle --version
  - '[ "$USE_BUNDLE_INSTALL" != "true" ] || retry bundle install --without postgres production --jobs $(nproc) "${FLAGS[@]}"'
  - '[ "$USE_DB" != "true" ] || bundle exec rake db:drop db:create db:schema:load db:migrate'